### ISSUE TITLE
AbapGit integration with Markeplace

### ISSUE THREAD

**Issue by andrecarrilho** [neptune-software/dxp-sap-edition-abapgit-extension#24]
Check if abapGit is installed and if the NEPTUNE abapGit extension is also installed in the system.

New class  ZCL_ABAPGIT_MARKET_INTEGRATION in package ZNEPTUNE_ABAPGIT_EXTENSION that will then be used in the marketplace API class /NEPTUNE/CL_NAD_MARKETPLACE.
Have a single point of entry because the call needs to be done dynamically, since the client may not have abapGit installed in the system.

- [x] Check abapgit and Neptune abapgit extension exists in the system;
- [x] Going into product check if product is already installed in the system ( table /NEPTUNE/MARKET ) and if REPO is present in abapGit

When installing 
- [x] If not installed, direct install,
- [x] If already installed and there is a new version ( UPDATE ) - first delete the current repo, then add the new one.

MARKETPLACE

- [x] When pressing "ADD REPO" button, if user is not logged in, prompt login popup
- [x] Create popup to insert PACKAGE ; DISPLAY NAME ; LABELS
- [x] Add new tab to insert github repo link
- [x] create new version if github link is ever changed
~~- [ ] download zip with TR~~
~~- [ ] download zip from repo~~

UNIT TEST
- [x] build a test where we add a proxy repo into abapgit , pull, check everything is there , delete 

QUESTIONS
- [x] where to insert this GitHub link (which table ) ?
- [x] where to construct proxy link ?

**Comment by hfgoncalves** [comment]
Is this status updated?

**Comment by andrecarrilho** [comment]
> Is this status updated?

The development is done for now.
The possibility of downloading the ZIP files for offline usage will not be included at the moment.
I didn't find a good way to do it.

I'll try to talk with David and Sofia from support today to see if they can do some testing to ensure the functionality is easy enough to work with and that no texts or buttons are displayed at the wrong time/place.

Once they give the ok with the testing, we plan to move into production and then create the first product using this functionality, the product being our abapGit extension itself 😁

Then I still have to write a blog post announcing that this is now available in the marketplace.


Does this sound good? Any comments or remarks?
